# Generated by Django 3.2.6 on 2021-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='사용자명')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록')),
            ],
        ),
    ]
