# Generated by Django 3.2.6 on 2021-09-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='memberarea',
            field=models.CharField(choices=[('A', 'Android 개발자'), ('I', 'iOS 개발자'), ('W', 'Web 개발자'), ('S', '서버 개발자'), ('WD', '디자이너 (Web UI/UX)'), ('AD', '디자이너 (App UI/UX)'), ('P', '기획자')], default='', max_length=64, null=True, verbose_name='지원분야'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberbirth',
            field=models.DateField(default='', null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberdepartment',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='학과'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberemail',
            field=models.EmailField(default='', max_length=128, null=True, verbose_name='이메일'),
        ),
        migrations.AddField(
            model_name='member',
            name='membergender',
            field=models.CharField(choices=[('M', '남성'), ('W', '여성'), ('Q', '선택안함')], default='', max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='member',
            name='membergrade',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년')], default='', max_length=64, null=True, verbose_name='학년'),
        ),
        migrations.AddField(
            model_name='member',
            name='membername',
            field=models.CharField(default='', max_length=64, null=True, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberphone',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='member',
            name='memberschool',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='학교'),
        ),
    ]
