# Generated by Django 3.2.6 on 2021-09-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210924_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberbirth',
            field=models.DateField(null=True, verbose_name='생일'),
        ),
    ]
