# Generated by Django 3.2.6 on 2021-09-24 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_member_memberbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberbirth',
            field=models.DateField(default='YYYY-MM-DD', null=True, verbose_name='생일'),
        ),
    ]
