# Generated by Django 3.2.6 on 2021-09-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_member_memberbirth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
