# Generated by Django 3.2.6 on 2021-09-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_user_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
    ]
