# Generated by Django 3.2.6 on 2021-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_user_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pub_date',
            new_name='userbirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)'), ('Q', '선택안함')], default='', max_length=1, null=True, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=64, verbose_name='이름'),
        ),
    ]
