# Generated by Django 3.2.6 on 2021-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20210924_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userbirth',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
    ]
