# Generated by Django 3.2.6 on 2021-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_user_userdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년')], default='', max_length=64, null=True, verbose_name='학년'),
        ),
    ]
