# Generated by Django 3.2.6 on 2021-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_user_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grade',
            new_name='usergrade',
        ),
        migrations.AddField(
            model_name='user',
            name='userarea',
            field=models.CharField(choices=[('A', 'Android 개발자'), ('I', 'iOS 개발자'), ('W', 'Web 개발자'), ('S', '서버 개발자'), ('WD', '디자이너 (Web UI/UX)'), ('AD', '디자이너 (App UI/UX)'), ('P', '기획자')], default='', max_length=128, null=True, verbose_name='지원분야'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userbirth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
    ]
