# Generated by Django 3.2.6 on 2021-09-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_auto_20210924_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userurl',
            field=models.URLField(blank=True, null=True, verbose_name='깃허브/블로그 url'),
        ),
    ]
